### ISSUE TITLE
Unable to access Direktiv using Istio

### ISSUE THREAD

**Issue by Shashankft9** [direktiv/direktiv#1700]
**Describe the bug**
When we are trying to access the direktiv UI using istio virtualservice and gateway, we are getting stuck on the very first screen where it shows the error as `There was an error fetching the namespaces`. Similar issue happens if I try to create a namespace as well.

**To Reproduce**
1. Install direktiv using the installation guide on kubernetes.
2. Have istio installed in the cluster and create virtualservice and gateway that resembles the default ingress created
3. access the `direktiv-frontend` service using istio

**Expected behavior**
The request should go to the `direktiv-flow` service from the frontend, but its not happening.

**Screenshots**
gw:
![image](https://github.com/user-attachments/assets/2a2e0080-f2ee-4045-b266-49c33ed7128e)

vs: 
![image](https://github.com/user-attachments/assets/9eacbb50-4140-49cc-a2ef-59cf6436da46)

the curl commands to the in cluster service works:
![image](https://github.com/user-attachments/assets/e5d3a576-b9a5-4ad5-a499-f5d6e58eeb2b)

added env variable in the `direktiv-frontend` deployment:
![image](https://github.com/user-attachments/assets/02d04f59-6d73-4742-8fe7-481f350e5ebe)

![image](https://github.com/user-attachments/assets/62ebd9f2-abf8-4b58-a706-d320edcaa880)
![image](https://github.com/user-attachments/assets/b9bfa3e7-acce-4a84-884f-2c4f58a37ded)

**Desktop (please complete the following information):**
 - OS: windoes
 - Browser: chrome
 - Version: latest

**Additional context**
this has been discussed in slack thread here: https://direktiv-io.slack.com/archives/C02NLR8UBSA/p1726056256698099
we are running kubernetes 1.28 with 2 nodes.

**Comment by h8718** [comment]
Hey,

Thank you for the detailed report!
Just a quick update: We've confirmed this as a bug and plan to start working on a fix next week.

**Comment by naveenthangaraj03** [comment]
@h8718 , By creating separate virtual service and gateway for ingress-nginx-controller we can able to access the direktiv UI 

Gateway for ingress-nginx-controller
![image](https://github.com/user-attachments/assets/2e8010d5-a280-4fb5-a232-34ed1d88d8df)

Virtual Service for ingress-nginx-controller
![image](https://github.com/user-attachments/assets/a4a58fe3-cc44-46f5-8f9c-8474b802594c)

Direktiv UI is access through fqdn created by vs and gateway for ingress-nginx-controller
![image](https://github.com/user-attachments/assets/36ae4e1d-4e6e-4c20-9fbd-71db207bfd22)

If we need to access the Direktiv UI, we need to create virtual service and gateway for both frontend and ingress-nginx-controller pod, but why it is not accessible with only virtual service and gateway of either frontend or ingress-nginx-controller pods respectively.

**Comment by h8718** [comment]
https://github.com/direktiv/direktiv/commit/4cad576852d7bbd4149078270814bacf8688d4af
should fix the issue, we added 

```
      - DIREKTIV_UI_PORT=8080
      - DIREKTIV_UI_BACKEND=http://flow:8181/api/
```

as parameters  they are present in the last release. 
I'll close the issue now, feel free to create a new if there is still a problem
