### ISSUE TITLE
Development of  reusable functions

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#205]
**Is your feature request related to a problem? Please describe.**

If a new image is pushed to the docker repository the "old" service of that function is still running. The service will use the new pushed image in development after ~2 minutes. That is too long if you develop/test a function. 

There has to be a "undeploy/redeploy" function button on the workflow view.

**Comment by trentis** [comment]
Is this still a problem? When changing the version in a reusable function definition a new one will get deployed. The only case I see that maybe still an issue if you are continuously pushing to v1/latest which could still warrant a redeploy button.
