### ISSUE TITLE
APIs to set registries for global functions.

### ISSUE THREAD

**Issue by alankm** [direktiv/direktiv#212]
We have namespaced registries, but how do we support custom registries for global functions? This needs expanding.

**Comment by alankm** [comment]
Should global registries be used only when creating global functions? Or should they act as a universal set of registries that can be used within every namespace?

Maybe both options should be possible?

@jensg-st

**Comment by jensg-st** [comment]
Universal is actually a good idea. It has to go into kube.go programmatically.

**Comment by alankm** [comment]
Feature added with f99b29d433d8fdef882f859307b17e74e4d10200
