### ISSUE TITLE
Unknown error message on incorrect logging field

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#334]
**Describe the bug**

If e.g. a logging fiels is incorrect the error message is not user friendly. The UI shows: ```update workflow: undefined```

**To Reproduce**

Add logging like this:

```
  log: "machine mark jq(.return."3".output.hardening_index | tonumber < 75)"
```

**Comment by alankm** [comment]
I don't think this error is reproducible with the latest release.
