### ISSUE TITLE
The broadcast service should add an ID if none is provided

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#344]
**Is your feature request related to a problem? Please describe.**

In testing scenarios is quite annoying to change the id for each request but even in normal API calls Direktiv should add an ID to a cloudevent if none is provided.

**Comment by alankm** [comment]
From the [cloudevents spec](https://github.com/cloudevents/spec/blob/v1.0.1/spec.md):

> Producers MUST ensure that source + id is unique for each distinct event.

Try posting your data directly to a workflow. If you need a cloudevent, your workflow can generate one for you.

**Comment by jensg-st** [comment]
It is for testing. I'm ok if we are saying if it is a 0 we will inject one for you. A random UUID is good enough. Writing a workflow to do test for one workflow seems to be overkill.

**Comment by alankm** [comment]
PR #349 has a tiny change to make this possible. It's filling it if it's undefined. What do you think? If you want to replace a keyword instead it's and easy change to make.
