### ISSUE TITLE
New ent schema will not migrate database gracefully.

### ISSUE THREAD

**Issue by jalfvort** [direktiv/direktiv#379]
**Describe the bug**

Upgrading to latest ent schemas will trigger the following error on postgres if it's using a older database.

```sh
2021-11-30 13:57:10.201 AEST [864] ERROR:  column "created_at" contains null values
2021-11-30 13:57:10.201 AEST [864] STATEMENT:  ALTER TABLE "refs" ADD COLUMN "created_at" timestamp with time zone NOT NULL
```

We need to investigate if its possible to adjust the migration process of ent to accommodate for this new column. Or if there is something we can change in the schema.

**Comment by jensg-st** [comment]
Maybe we should have an init container which checks the database schema version and the updates the steps between the actual version and the one needed by flow/funtions etc. For now on main we can just run the init container to update from 0.5.x to 0.6.0.

**Comment by jensg-st** [comment]
I have created a WIP PR for this. An init-container which can update the database manually if required.

**Comment by jalfvort** [comment]
I've had a look at the pr and it fixes the original problem created by the `created_at`. From what I understand we need to somehow know both the current version of the database tables and the current flow version. The current flow version is easy enough as it's something that exists in the helm values. But a record of the current database version is not stored anywhere (at least to my knowledge), and would probably need to be stored in the database itself.

What I'm thinking:
* Add a table to our database that keeps a record of current and previous versions of the database. [To clarify, by version I mean something like v.0.6.0]
* On init container compare current helm version tag with current version from the database. If database version is older than the current helm, then execute all manual migration upgrades from db version to latest/current helm version. Finally, update db table and set current database version to current helm version.
* Limitation: This can only upgrade forward. You will not be able to downgrade gracefully (Technically we could also handle this, but I don't think it's worth the effort of inversing the upgrade steps.)

**Comment by jensg-st** [comment]
I agree. I left that open for you and Alan to assess and implement. At the moment it can only do forward as you said but I think that is the only way we need. I think we store the generation in the database and on startup we compare it with the generation in flow. That is how it is implemented, assuming we get the difference of generations on startup.
