### ISSUE TITLE
Getting instances for the workflow using filters

### ISSUE THREAD

**Issue by trentis** [direktiv/direktiv#388]
If I name my workflow 'test' it'll also pick up any instance that is using the revision 'latest'. Maybe we need to add another field or split the as into path and revision.

```
${url}namespaces/${namespace}/instances?filter.field=AS&filter.type=CONTAINS&filter.val=${path.substring(1)}
```

**Comment by jensg-st** [comment]
Tbh, I don't understand what that means.

**Comment by trentis** [comment]
list of instances returns an 'as' field. We don't actually have an api to list instances for the workflow. The above URL filters using ent to get the workflow details.  The 'as' field can appear as 'workflow' or 'workflow:revision'

```
test
direktiv-request:latest
```
If i filter the instances list by 'test' using the 'as' column the above two workflows would get picked up. Where I am actually only after test and all of its revisions that have been executed in the list.
