### ISSUE TITLE
Update Helm charts to make ingress-nginx more configurable

### ISSUE THREAD

**Issue by bradmccoydev** [direktiv/direktiv#394]
# Update Helm charts to make ingress-nginx more configurable

**Given** we want to try out Direktiv in Kubernetes
**When** we install the dependencies
**Then** we want the ability to be able to bring our own ingress-nginx, and set our own annotations for the ingress so for things like external dns, cert manager etc.

### API Ingress Manifest
charts/direktiv/templates/ingress-api.yaml
- [ ] Add Annotations to charts/direktiv/values.yaml under ingress line 92 for ingress-api.yaml

### UI Ingress Manifest
charts/direktiv/templates/ingress-ui.yaml
- [ ] Add Annotations to charts/direktiv/values.yaml under ingress line 92 for ingress-ui.yaml

Note: it could be better to put the ingress configuration under the ui: and api: as it will make it scalable for the future 

### Add ingress-nginx dependency as optional
charts/direktiv/Chart.yaml
- [ ] Have a flag for whether you install the ingress-nginx or not.

**Comment by bradmccoydev** [comment]
I will pick this up. @jensg-st please assign this to me.

**Comment by jensg-st** [comment]
Thanks for that. I have assigned the issue.

**Comment by bradmccoydev** [comment]
PR raised: https://github.com/direktiv/direktiv-charts/pull/1

**Comment by bradmccoydev** [comment]
PR merged, we can now close this issue

**Comment by jensg-st** [comment]
Thanks Brad
