### ISSUE TITLE
Update Readme on helm chart repo to be easier for first time contributors

### ISSUE THREAD

**Issue by bradmccoydev** [direktiv/direktiv#396]
**Given** we want to get more open source contributors
**When** we want to teach people helm and Direktiv
**Then** we need to make our readme easy for people forking the project

Repo: https://github.com/direktiv/direktiv-charts

Acceptance criteria:
- reference readme's in the helm charts
- add git helper guide
- add a brief description

**Comment by bradmccoydev** [comment]
Please assign this to me

**Comment by bradmccoydev** [comment]
PR raised: https://github.com/direktiv/direktiv-charts/pull/2

**Comment by jensg-st** [comment]
merged
