### ISSUE TITLE
Update Direktiv helm chart to make prometheus optional

### ISSUE THREAD

**Issue by bradmccoydev** [direktiv/direktiv#397]
**Given** we want to try out Direktiv in Kubernetes
**When** we install the dependencies
**Then** we want the ability to be able to bring our own prometheus so we can add more configurations etc.

Acceptance criteria:
Have a flag for whether you install the Prometheus or not.

update line 199 charts/direktiv/values.yaml to have a configuration of whether to install or not.
insert newline in charts/direktiv/Chart.yaml

# Testing
update charts/direktiv/values.yaml for whether to install prometheus or not

helm dependency update charts/direktiv/
helm install --debug --dry-run charts/direktiv --generate-name

@bradmccoydev will be mentoring @benhpoh this issue to teach him helm

**Comment by benhpoh** [comment]
I'll pick up this task with @bradmccoydev

**Comment by bradmccoydev** [comment]
PR raised: https://github.com/direktiv/direktiv-charts/pull/2

**Comment by jensg-st** [comment]
merged
