### ISSUE TITLE
Namespace character limit not working

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#406]
**Describe the bug**

Ent has a limit of 64 characters for namespaces but that doesn't seem to work properly. I

**To Reproduce**

Create a namespace with 64+ characters

**Expected behavior**

Error from the API / GRPC layers.

**Comment by alankm** [comment]
This seems like a perfectly reasonable limitation to add to me. But just as a sanity check, can you please tell me why you think this?

> Ent has a limit of 64 characters for namespaces

As far as I can tell that's not true at all.

**Comment by jensg-st** [comment]
I thought I did see it in the schema source. Maybe Im wrong.

**Comment by alankm** [comment]
Resolved with #410.
