### ISSUE TITLE
Tagged version getting deleted if "source" is getting deleted

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#413]
**Is your feature request related to a problem? Please describe.**

At the moment if a user deletes a "source" revision all tags pointing to that revision are getting deleted too. That might lead to unwanted deletion of service revisions. 

The easiest solution is not t allow deletion of revisions with tags so the tags need to be deleted first before a "source" revision can be deleted.

**Comment by alankm** [comment]
Resolved with #414
