### ISSUE TITLE
Azure Event Subscription not working

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#434]
Configuring the Azure environment to send events to the direktiv instance using a webhook configuration (as detailed in the documents) is not working

1. Log on to the Azure Portal and navigate to Home->Storage Accounts-> {Storage Account}->Events
2. Using an Azure Cloud Shell (icon top right in the blue ribbon bar) run the following command to configure the Event Subscription
3. `az eventgrid event-subscription create --name demo-direktiv-simple-workflows --source-resource-id=$(az storage account show --name {storage account name} --resource-group {resource group name} --query id --output tsv) endpoint=https://demo.direktiv.io/api/namespaces/simple-workflows/broadcast --endpoint-type=webhook --event-delivery-schema cloudeventschemav1_0 --delivery-attribute-mapping Authorization Static "Bearer {TOKEN HERE}" true`
3. You should now see the event subscription created in the Azure Portal
4. Upload a file to a container in the Home->Storage Accounts-> {Storage Account}->Containers
5. Expected to see an event in direktiv namespace

**Comment by jensg-st** [comment]
The events doc has been updated: 

https://github.com/direktiv/direktiv.github.io/blob/master/docs/events/index.md

Additionally there is an additional header required for Azure and it will be in the 0.6.1 release
