### ISSUE TITLE
Secrets with Hyphen in Name Fail

### ISSUE THREAD

**Issue by agardnerIT** [direktiv/direktiv#452]
**Describe the bug**
Secret names that contain `-` fail. Underscores and camelcase work. There is no warning in the UI when creating secrets with hyphens and the UI allows it.

**To Reproduce**
1. Create a secret called `foo-bar`
2. Create a simple workflow as shown below
3. Run the workflow

**Expected behavior**
The workflow either runs with secret names that contain hyphens OR secret names containing hyphens are blocked from ever being created.

```
[ 11:42:23.229 ]
Preparing workflow triggered by API.
[ 11:42:23.244 ]
Running state logic (step:1) -- get-details
[ 11:42:23.246 ]
Decrypting secrets.
[ 11:42:23.257 ]
Instance failed with uncatchable error: failed to evaluate jq: error in 'headers': error in 'x-token': error running jq query beginning at offset 0: function not defined: bar/0
```

** Workflow **
```
description: My first workflow
functions:
- id: get-metadata
  type: reusable
  image: direktiv/request:v1
states:
- id: get-details
  type: action
  action:
    secrets: ["foo-bar"]
    function: get-metadata
    input:
      method: "GET"
      url: "https://mysite.com/someAPIEndpoint"
      headers:
        "x-token": "jq(.secrets.foo-bar)"
```

**Comment by jensg-st** [comment]
Thanks for raising that issue but this is jq behavior. In this case jq sees that as *foo -bar = X*.

If you want to use hyphens in jq they have to be quoted. In this case jq(.secrets."foo-bar").
