### ISSUE TITLE
Function cleanup does not work

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#528]
**Describe the bug**

Direktiv creates, modifies and deletes functions used in a flow. The delete part does not seem to work and function stay linked in the overview tab.

**Comment by jensg-st** [comment]
As mentioned on slack, then cleanup has issues with tagged workflows. As an example if a workflow has been tagged and the active revision has a new function with a different tag.

**Comment by alankm** [comment]
Isn't this working as intended? If multiple revisions exist, each still needs to be runnable. If nobody uses it knative can keep the services defined without wasting resources on live containers. 

Right now the logic keeps functions defined for every revision. What is the preferred behaviour?

**Comment by jensg-st** [comment]
Should move into functions pod
