### ISSUE TITLE
API does not allow POST request without op= set

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#583]
**Describe the bug**
 
A simple API call (POST) like the following: 

```
https://MYSERVER/api/namespaces/test/tree/bash?input.sleep=2
```

returns with 405 method not allowed. It says op is default exec but that does not seem to be the case.

**Comment by alankm** [comment]
`op` is not an optional argument, and if it wasn't provided (like in your example URL) this isn't expected to execute anything. There is no default value.

**Comment by jensg-st** [comment]
misunderstanding in docs
