### ISSUE TITLE
Extend generateEvent capability to send events to different direktiv instances

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#597]
Have distributed direktiv instances, allowing event-based communication between these instances without the need to start a container (or add yet another state).

**Describe the solution you'd like**
Would like an option to add multiple target endpoints as part of generateEvent which has:
1. target IP/URL
2. namespace
3. auth token

**Describe alternatives you've considered**
Start a container which can do the work for us, but since this is an internal Direktiv action shouldn't it be part of the generateEvent configuration. I don't want to add another container to the list of prerequisites?

**Comment by jensg-st** [comment]
We have knative eventing support and it is possible to communicate via knative eventing between two instances.
