### ISSUE TITLE
Remove the dependency graph.

### ISSUE THREAD

**Issue by alankm** [direktiv/direktiv#614]
As more and more things in the Direktiv workflow YAML have become dynamic (jq-able), the value of the existing dependency graph logic has gotten less helpful. If we want to restore this kind of feature we need an entirely different approach. For now, we should remove this neglected logic from Direktiv.

**Comment by alankm** [comment]
I've pushed branch `remove_dg` with the backend changes necessary for this.

**Comment by jalfvort** [comment]
Resolved in PR: https://github.com/direktiv/direktiv/pull/624
