### ISSUE TITLE
Add a direktiv ignore file for mirror functionality

### ISSUE THREAD

**Issue by alankm** [direktiv/direktiv#623]
I think it's inevitable that the mirror logic should need to be more configurable, so I think we should add some sort of optional configuration file with a fixed name to the root of a repository that the logic will read for instructions. Among other things, this could be used to implement an analogous feature to the git ignore file. So that we can include unrelated YAML files in our repositories.

**Comment by jalfvort** [comment]
Accidental close

**Comment by alankm** [comment]
@jensg-st What do you think is the best way to handle errors here? For example, the user has added an ignore file that doesn't parse or with dodgy glob patterns. 

Is it better to abort the sync? Or to proceed as if the ignore file didn't exist?

I think we can and should log these issues either way.
