### ISSUE TITLE
Validate State's 'schema' is misdocumented.

### ISSUE THREAD

**Issue by alankm** [direktiv/direktiv#65]
The documentation & structs suggest that you can define a global schema and reference it, but no logic appears to implement it this way. We should fix either the implementation or the documentation.

**Comment by jalfvort** [comment]
Do we want to cut this out or implement it? As far as I can tell there's only two ways to implement this:
1) Schemas validate workflow input when executed. But you can already do this by setting your first state as a validate state.
2) Schemas are used only by the validate state by referencing the id. This would save on some yaml duplication if a workflow is gonna validate the same schema multiple times. 

If we go with No. 2 we do something like this
```
- id: validate-input
  type: validate
  ref: schema-age
```

**Comment by alankm** [comment]
Cut it IMO.
