### ISSUE TITLE
Add folder functionality and update to secrets

### ISSUE THREAD

**Issue by jensg-st** [direktiv/direktiv#681]
**Is your feature request related to a problem? Please describe.**

Secrets is as simple list at the moment. The idea is to use "virtual folders". If a secret is stored under `hello/world` it is basically stored in a folder called `hello`.

**Features**

- Secrets  stored in virtual folders
- Replace secret values instead of delete/create
- Search secrets
- "Secret" input field instead of plain text
- Delete "folder"

**Backend**

- [ ] Search function 
- [ ] Get function based on Prefix
- [ ] Delete function based on prefix incl. folder delete
- [ ] Update secret functionality

**UI**

- [ ] #683
- [ ] Provide toggle to hide secret input when creating a new secret
- [ ] Add button to re-create secret
- [ ] Add search bar

**Comment by jensg-st** [comment]
**StoreSecret(ctx context.Context, in secretsgrpc.SecretsStoreRequest)**

- Remove 32 character limit (reason why it exists?)
- Check if it exists as folder (should we allow folder and secrets with the same name?)

**RetrieveSecret(ctx context.Context, in secretsgrpc.SecretsRetrieveRequest)**

- No change

**GetSecrets(ctx context.Context, in secretsgrpc.GetSecretsRequest)**

- Add prefix parameter for in-folder search, e.g. /myfolder

**DeleteSecret(ctx context.Context, in secretsgrpc.SecretsDeleteRequest)**

- No change

**DeleteSecrets(ctx context.Context, in secretsgrpc.DeleteSecretsRequest)**

- Additional boolean to confirm folder delete

**Search function does not exist**

**Comment by Fxrdf** [comment]
Isn't better to Rename GetSecrets to GetNamespaceSecrets and use the RetrieveSecret method also for folder ?
