### ISSUE TITLE
use docker quickstart take time too long

### ISSUE THREAD

**Issue by zzqliwei** [direktiv/direktiv#700]
![image](https://user-images.githubusercontent.com/8856859/199937639-491de0c9-c33e-4468-9367-9367a9f6eed7.png)
when I execute the command
docker run --privileged -p 8080:80 -p 31212:31212 -d --name direktiv direktiv/direktiv-kube
it take me one day,and retry more times.

**Comment by jensg-st** [comment]
Hi, the images are mostly preloaded and that shouldn't happen. Have you tried to set 'sudo sysctl fs.inotify.max_user_instances=4096'? If pods are pending that is usually the case and you need to run this command to increase it.

**Comment by jensg-st** [comment]
I'm assuming that worked or is not an issue anymore?
