### ISSUE TITLE
Cannot re-trigger event received: error: "send namespace event: method is not allowed"

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#701]
**Describe the bug**
Received an event from Google Cloud EventArc via the Direktiv container as described in the document. The event is received and can execute a workflow. When I try and trigger the event again the following error appears:

"send namespace event: method is not allowed"

Example the event input is shown below (not the data is binary - something wrong in the direktic google eventarc container code):

Context Attributes,
  specversion: 1.0
  type: google.cloud.audit.log.v1.written
  source: //cloudaudit.googleapis.com/projects/exalted-iridium-367300/logs/activity
  id: projects/exalted-iridium-367300/logs/cloudaudit.googleapis.com%2Factivityr7a0hndbrmi1667689902263958
  time: 2022-11-05T23:11:42.837387365Z
  datacontenttype: application/json
Data (binary),
  {
    "protoPayload": {
      "authenticationInfo": {
        "principalEmail": "wilhelm.wonigkeit@direktiv.io"
      },
      "requestMetadata": {
        "callerIp": "2601:643:4001:4c0:9c47:2941:e9b5:bc90",
        "callerSuppliedUserAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36,gzip(gfe),gzip(gfe)"
      },
      "serviceName": "compute.googleapis.com",
      "methodName": "v1.compute.instances.delete",
      "resourceName": "projects/exalted-iridium-367300/zones/us-central1-a/instances/instance-template-1",
      "serviceData": {},
      "request": {
        "@type": "type.googleapis.com/compute.instances.delete"
      }
    },
    "insertId": "r7a0hndbrmi",
    "resource": {
      "type": "gce_instance",
      "labels": {
        "instance_id": "3705468946020520950",
        "zone": "us-central1-a",
        "project_id": "exalted-iridium-367300"
      }
    },
    "timestamp": "2022-11-05T23:11:42.263958Z",
    "severity": "NOTICE",
    "logName": "projects/exalted-iridium-367300/logs/cloudaudit.googleapis.com%2Factivity",
    "operation": {
      "id": "operation-1667689855034-5ecc14d67a55a-625b9bf3-04683458",
      "producer": "compute.googleapis.com",
      "last": true
    },
    "receiveTimestamp": "2022-11-05T23:11:42.837387365Z"
  }

**Comment by wwonigkeit** [comment]
This is the example id causing the problem:

```
Context Attributes,
  specversion: 1.0
  type: google.cloud.audit.log.v1.written
  source: //cloudaudit.googleapis.com/projects/exalted-iridium-367300/logs/activity
  id: projects/exalted-iridium-367300/logs/cloudaudit.googleapis.com%2Factivityh7g20fd62js1667692509297641
  time: 2022-11-05T23:55:10.168908558Z
  datacontenttype: application/json
```

**Comment by alankm** [comment]
`id: projects/exalted-iridium-367300/logs/cloudaudit.googleapis.com%2Factivityr7a0hndbrmi1667689902263958`
This appears to be the cause of the problem. Our event replay handler doesn't support slashes in the event ID.

**Comment by wwonigkeit** [comment]
https://dev.direktiv.io/api/namespaces/test-snc/events/projects/exalted-iridium-367300/logs/cloudaudit.googleapis.com/activityh7g20fd62js1667692509297641/replay
