### ISSUE TITLE
How can we create a  function to do CI job

### ISSUE THREAD

**Issue by westwind027** [direktiv/direktiv#728]
I want to use direktiv to do some ci job in serverless worker , but after I look up the function document([link](https://docs.direktiv.io/spec/workflow-yaml/functions/#functiondefinition)), I find  we cannot mount something to pod, so we cannot do docker in docker , that means we cannot use docker or podman to operate image.   How can we create a function to do CI job now  ?

**Comment by jensg-st** [comment]
Hi, I can see two requirements here. To do nested containers you need to run the pods in privileged mode. Is that what you are referring to? The mount of additional disk is a build requirement? Is it because the default disk size is too small?

**Comment by westwind027** [comment]
---"Hi, I can see two requirements here. To do nested containers you need to run the pods in privileged mode. Is that what you are referring to?"

Yes, to do this , I need the specification support like this ：

functions:
- id: buildjob
  image: westwind027/bash:v5
  type: knative-workflow
  mount:  /var/run/docker.sock:/var/run/docker.sock

so I can use docker or podman  in pod to build the dockfile and push the image to registry 

---"The mount of additional disk is a build requirement? Is it because the default disk size is too small?"

I don't mean to that, but maybe it's also a problem when image is big.  so mount  flag also can use to solve this kind problem.

After I rethink about this problem, I find a solution to resolve now,  I can install a framework on k8s  just like tekton, or jenkins ci runner , then use direktiv to interact with them. But I think if we can extent function's specific will be more flexible

**Comment by jensg-st** [comment]
For building containers we are doing the same and using google cloud as external build system. Nevertheless I'm tracking this feature in #729 as a discussion. 

Btw, the disk size can be changed now and that should not be a problem right now.

**Comment by westwind027** [comment]
Got it ,👍
