### ISSUE TITLE
Direktiv Repository Mirror: GitLab user and PAT token not being used

### ISSUE THREAD

**Issue by wwonigkeit** [direktiv/direktiv#746]
We're using GitLab as the workflow repository. If we want to sync to GitLab (in our mirroring) then we need to be able to support the following type of configuration:

<img width="341" alt="Screenshot 2023-01-23 at 6 26 30 pm" src="https://user-images.githubusercontent.com/11344997/214201471-b0c85bb1-8159-496c-afd4-092a79828168.png">

We created a PAT token, but we cannot get it working without actually having the token completely visible in the URL
so something like: 

https://**wwonigkeit**:**tokenhere**@gitlab.dell.com/wwonigkeit/direktiv-workflows

There needs to be an option to configure a username as part of the mirror configuration, however, not sure how this will affect the GitHub syncrhonisation?

**Comment by jensg-st** [comment]
Fixed in 0.7.1-rc1
