### ISSUE TITLE
Simplify golangci

### ISSUE THREAD

**Issue by sir-hassan** [direktiv/direktiv#748]
## Summery
Remove unnecessary lint image and provide solid golangci local run.

**Comment by jensg-st** [comment]
We actually should use a docker image to make sure it is always the same version and same config.

**Comment by sir-hassan** [comment]
There is already an official golang-ci docker image, but we can’t use it because it fails due to the libgit2. Once we remove it (merging the PR), we will be able to use the official golang-ci image without the need to build our own one.
