### ISSUE TITLE
[install-document] install postgres failed

### ISSUE THREAD

**Issue by stubbornTanzhe** [direktiv/direktiv#789]
**Describe the bug**

**To Reproduce**
1. Go to '[install postgres](https://docs.direktiv.io/installation/database/#basic-configuration)'
2. execute the command 'kubectl apply -f https://raw.githubusercontent.com/direktiv/direktiv/main/kubernetes/install/db/basic.yaml
'

**Expected behavior**
install postgres success, postgres pod status is running

**Screenshots**
```
[CMCC.DESKTOP-FL84U1K] ➤ kubectl get pod -n postgres
NAME                           READY   STATUS             RESTARTS        AGE
pgo-596769795b-jx2gd           0/1     CrashLoopBackOff   224 (77s ago)   18h
pgo-upgrade-6dc9696bf6-nzgtm   1/1     Running            0               18h

kubectl logs -f pgo-596769795b-jx2gd -n postgres
...
...
panic: no matches for kind "CronJob" in version "batch/v1beta1"

goroutine 1 [running]:
main.assertNoError(...)
        github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:41
main.main()
        github.com/crunchydata/postgres-operator/cmd/postgres-operator/main.go:105 +0x570
```

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [docker-desktop]
 - Version [k8s:1.25]

**Additional context**
is there something missing in the latest version? such as the CronJob object

**Comment by jensg-st** [comment]
Thanks for reporting this. We have updated the postgres charts and after a `helm repo update` it should work now. The charts were not compatible with the latest version of k3s. Please let me know if that resolves your issue.

**Comment by stubbornTanzhe** [comment]
Thank you for the timely response, I exec `helm repo remove` `helm repo add` `helm repo update` and the pod works now.
thx so much;)

**Comment by stubbornTanzhe** [comment]
```docker pull registry.developers.crunchydata.com/crunchydata/crunchy-pgba:ubi8-2.41-4
Error response from daemon: manifest for registry.developers.crunchydata.com/crunchydata/crunchy-pgba:ubi8-2.41-4 not found: manifest unknown: manifest un
known```
seems that next step the image not exist @jensg-st

**Comment by stubbornTanzhe** [comment]
porblem solved
