### ISSUE TITLE
Support docker swarm?

### ISSUE THREAD

**Issue by dazinator** [direktiv/direktiv#999]
**Is your feature request related to a problem? Please describe.**
Kubernetes is not suited for every organisation.
Swarm can be much simpler for many.
I would love to use direktiv but not if I need to first embed kubernetes. Would it be possible to support swarm in future?

**Describe the solution you'd like**
Would be good if this worked on swarm.
From your getting started docs I gathered following issues with running on swarm:

- There is no support for Pods so this means no easy approach to run sidecars- that is "co-located" containers. However I dont think co location is absolutely necessary to get this functioning on swarm - the "function" container when deployed as a swarm service instead of a k8's one, and attached to an appropriate direktiv docker network, can be sent a http request directly from direktiv based on its service name. E.g http://service-a:8080 its potentially added latency vs using localhost but still workable?

**Describe alternatives you've considered**
Being inspired to build a docker swarm alternative.

**Additional context**

**Comment by jensg-st** [comment]
Hi, 

thanks for your feedback and an interesting timing to ask that question. We are working on a 0.8.0 release where a big focus is a new UI but we are working on the back-end too. The back-end changes are focused on two items:

- Remove Postgres dependency

We are using Postgres for Pub/Sub for cluster communication and Postgres locks for distributed locking. For 0.8.0 we are replacing the Pub/Sub part with a different solution and 0.8.1 should remove the locking requirements. After that change Direktiv should run on pretty much any database. 

- Remove Knative dependency

The second focus point is removing the Knative dependency. Our core system is not requiring Kubernetes at all. It is just the action/function part which does. In this case it is Knative. Although we will keep Knative as the default implementation, we are basically introducing an interface for that. The idea is to provide implementations for Knative, (plain) Docker, Swarm or Nomad. This is for 0.8.1 as well. The release is in September this year, but exact time frame hasn't been agreed on. 

Thanks
